In [16]:
#construct a decision tree classifier. ~99% accuracy from cross validation

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [55]:
feature_names,datalabels=np.load('data1.npy')

#shuffle data
np.random.shuffle(datalabels)

traindata2=datalabels[:,:98]
trainlabels2=datalabels[:,-1]

cls=DecisionTreeClassifier()
cls.fit(traindata2,trainlabels2)

cross_val_score(cls, traindata2, trainlabels2)

array([0.9972067 , 0.99160839, 0.99156118])

In [13]:
y=cls.feature_importances_
[(feature_names[i],y[i]) for i in range(len(y))]

[('heart_rate_mean', 0.008618202088658348),
 ('heart_rate_std', 0.0),
 ('hand_temp_mean', 0.0),
 ('hand_temp_std', 0.0),
 ('hand_a16_x_mean', 0.08348618863158211),
 ('hand_a16_x_std', 0.0),
 ('hand_a16_y_mean', 0.003074570536179073),
 ('hand_a16_y_std', 0.09336674969026124),
 ('hand_a16_z_mean', 0.10225902737783298),
 ('hand_a16_z_std', 0.0),
 ('hand_a16_freq_0.5', 0.0),
 ('hand_a16_freq_0.75', 0.048855417527862814),
 ('hand_a16_freq_0.9', 0.0),
 ('hand_a16_freq_0.95', 0.002034945591760265),
 ('hand_gyro_x_mean', 0.0),
 ('hand_gyro_x_std', 0.0),
 ('hand_gyro_y_mean', 0.0),
 ('hand_gyro_y_std', 0.0),
 ('hand_gyro_z_mean', 0.0),
 ('hand_gyro_z_std', 0.0),
 ('hand_gyro_freq_0.5', 0.0),
 ('hand_gyro_freq_0.75', 0.0),
 ('hand_gyro_freq_0.9', 0.0),
 ('hand_gyro_freq_0.95', 0.0),
 ('hand_B_x_mean', 0.0),
 ('hand_B_x_std', 0.0),
 ('hand_B_y_mean', 0.0),
 ('hand_B_y_std', 0.0),
 ('hand_B_z_mean', 0.0),
 ('hand_B_z_std', 0.001756897449245185),
 ('hand_B_freq_0.5', 0.0),
 ('hand_B_freq_0.75', 0.0

In [21]:
feature_names,datalabels=np.load('data2.npy')

#shuffle data
np.random.shuffle(datalabels)

traindata2=datalabels[:,:98]
trainlabels2=datalabels[:,-1]


cls=DecisionTreeClassifier()
cls.fit(traindata2,trainlabels2)

cross_val_score(cls, traindata2, trainlabels2)

array([0.99737533, 0.99473684, 0.99734748])

In [22]:
traindata2.shape

(2276, 98)

In [267]:
#import feature_extraction

#for i in range(1,10):
#    feature_extraction.extract(i)

In [56]:
datalabels=[]
for i in range(1,10):
    feature_names,datalabelsi=np.load('data'+str(i)+'.npy')
    datalabels.append(datalabelsi)

In [57]:
[x.shape for x in datalabels]

[(2142, 99),
 (2276, 99),
 (1463, 99),
 (2007, 99),
 (2366, 99),
 (2166, 99),
 (1994, 99),
 (2261, 99),
 (0, 99)]

In [58]:
datalabels=np.vstack(datalabels)

In [59]:
#shuffle data
np.random.shuffle(datalabels)

traindata2=datalabels[:,:98]
trainlabels2=datalabels[:,-1]


cls=DecisionTreeClassifier()
cls.fit(traindata2,trainlabels2)

cross_val_score(cls, traindata2, trainlabels2)

array([0.99083393, 0.98776098, 0.98865887])

In [60]:
y=cls.feature_importances_
a=[[feature_names[i],y[i]] for i in range(len(y))]
a.sort(key=lambda x:-x[1])

In [62]:
a

[['ankle_a16_x_mean', 0.21754147568365037],
 ['chest_B_y_mean', 0.1119754118150711],
 ['hand_a16_freq_0.95', 0.10966387655151136],
 ['chest_a16_y_std', 0.08497537463950695],
 ['hand_a16_x_mean', 0.08138982268344559],
 ['chest_gyro_y_std', 0.06870897764681787],
 ['hand_gyro_freq_0.95', 0.06750847872514605],
 ['ankle_a16_x_std', 0.05262655278392277],
 ['chest_gyro_y_mean', 0.029591387134234145],
 ['ankle_gyro_z_std', 0.025650664848947968],
 ['chest_a16_z_mean', 0.021532397489075004],
 ['ankle_gyro_freq_0.5', 0.019471028927796986],
 ['chest_temp_mean', 0.015418065295319208],
 ['hand_temp_mean', 0.012906523293183958],
 ['chest_B_z_mean', 0.009961784710772746],
 ['ankle_gyro_y_std', 0.008742065808737463],
 ['hand_a16_z_mean', 0.008071911518487955],
 ['hand_B_x_mean', 0.005932898646654965],
 ['ankle_gyro_y_mean', 0.00576913833809227],
 ['chest_a16_z_std', 0.005263032040571024],
 ['hand_gyro_x_std', 0.004869918844959939],
 ['ankle_temp_mean', 0.003438246949506799],
 ['hand_a16_y_mean', 0.0033