In [23]:
import multiprocessing
import time
import os
import numpy as np

In [24]:
print(multiprocessing.cpu_count())

4


In [25]:
max_number_processes = 2
pool = multiprocessing.Pool(max_number_processes)

In [26]:
#Make the first generation 
old_generation = np.zeros([10,10])
for i in range(10):
    old_generation[i,:] = np.random.binomial(1,0.5,10)

In [27]:
old_generation

array([[0., 0., 1., 1., 0., 0., 0., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 1.],
       [0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
       [1., 0., 1., 1., 1., 1., 0., 1., 0., 0.],
       [1., 1., 1., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 1., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 0., 1., 0., 1.]])

In [30]:
nprocs = 3

In [32]:
np.array_split(old_generation,nprocs)

[array([[0., 0., 1., 1., 0., 0., 0., 1., 1., 0.],
        [0., 1., 1., 1., 1., 0., 0., 0., 1., 1.],
        [1., 0., 0., 1., 1., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 1., 0., 0., 0., 0., 1.]]),
 array([[0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
        [1., 0., 1., 1., 1., 1., 0., 1., 0., 0.],
        [1., 1., 1., 0., 0., 1., 0., 0., 0., 0.]]),
 array([[0., 1., 1., 0., 1., 0., 1., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 1., 1., 1.],
        [1., 0., 1., 1., 0., 1., 0., 1., 0., 1.]])]